### ISSUE TITLE
app indicator icon does not show up

### ISSUE THREAD

**Issue by fds2610** [ba0f3/gnome-bluetooth-smartlock#5]
hi, on debian 11 I installed this app via gnome shell extensions plugin in firefox and afterwards via sourcecode-git-make.
in both scenarios the software installed without an error, but the app indicator icon does not show up. Now i can see an error message in syslog:
JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownProperty: Property org.kde.StatusNotifierItem.IconAccessibleDesc was not found in object /StatusNotifierItem#012_promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:446:45#012### Promise created here: ####012getProxyProperty@/home/<localuser>/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:55:31#012refreshPropertyOnProxy@/home/<localuser>/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:73:39#012_translateNewSignals/<@/home/<localuser>/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:268:18#012_translateNewSignals@/home/<localuser>/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:267:50#012_onProxySignal/<@/home/<localuser>/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:294:56#012_onProxySignal@/home/<localuser>/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:294:38#012async*AppIndicatorsAppIndicator/<@/home/<localuser>/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:105:76
what can i do to solve this issue?

**Comment by ba0f3** [comment]
I don't think problem comes from my extension. Can you please try to disable your AppIndicator extension?

**Comment by fds2610** [comment]
thx for that hint. after changing a couple of things it works now.
